
POST http://localhost:3333/locations HTTP/1.1
content-type: application/json

{
	"name": "Maria eduarda eeeee",
	"email": "ee@gmail.com",
	"whatsapp": "095955ee9595959",
	"latitude": -23.0003709,
	"longitude": -43.365895,
	"city": "Rio de janeiro",
	"uf": "RJ",
	"items": [1,4]
}

###
GET http://localhost:3333/locations/1 HTTP/1.1

###
GET http://localhost:3333/locations?city=Rio%20de%20janeiro&uf=RJ&items=11 HTTP/1.1

###
GET http://localhost:3333/locations HTTP/1.1
content-type: application/json

{
	"city": "Rio de janeiro",
	"uf": "RJ",
	"items": 9
}
###
POST http://localhost:3333 HTTP/1.1
Content-Type: application/json
Authorization: Basic xxx

###
PUT http://localhost:3333/locations/1 HTTP/1.1
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png
